import streamlit as st

st.title("Mi Proyecto MNIST de Google Colab")
st.write("Cargando los datos del entrenamiento...")
# -*- coding: utf-8 -*-
"""Copia de mnist_convnet

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JvdH_WS5vsc2EJfk5Fy6Mifrm7tuZLEB

# Simple MNIST convnet

**Author:** [fchollet](https://twitter.com/fchollet)<br>
**Date created:** 2015/06/19<br>
**Last modified:** 2020/04/21<br>
**Description:** A simple convnet that achieves ~99% test accuracy on MNIST.

## Setup
"""

import numpy as np
import keras
from keras import layers
import tensorflow as tf
from tensorflow import keras

"""## Prepare the data"""

# Model / data parameters
num_classes = 10
input_shape = (28, 28, 1)

# Load the data and split it between train and test sets
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

# Scale images to the [0, 1] range
x_train = x_train.astype("float32") / 255
x_test = x_test.astype("float32") / 255
# Make sure images have shape (28, 28, 1)
x_train = np.expand_dims(x_train, -1)
x_test = np.expand_dims(x_test, -1)
print("x_train shape:", x_train.shape)
print(x_train.shape[0], "train samples")
print(x_test.shape[0], "test samples")


# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

"""## Build the model"""

model = keras.Sequential(
    [
        keras.Input(shape=input_shape),
        layers.Conv2D(32, kernel_size=(3, 3), activation="relu"),
        layers.MaxPooling2D(pool_size=(2, 2)),
        layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
        layers.MaxPooling2D(pool_size=(2, 2)),
        layers.Flatten(),
        layers.Dropout(0.5),
        layers.Dense(num_classes, activation="softmax"),
    ]
)

model.summary()

"""## Train the model"""

import os
from tensorflow import keras

# =====================================================================
# 1. DEFINICIÓN DE RUTAS (Aquí organizas tus carpetas)
# =====================================================================
carpeta_principal = "proyecto_mnist"
ruta_checkpoint = f"{carpeta_principal}/checkpoints/modelo_mnist.keras"
ruta_logs = f"{carpeta_principal}/logs_tensorboard"

# Creamos las carpetas automáticamente para que no marquen error
os.makedirs(f"{carpeta_principal}/checkpoints", exist_ok=True)
os.makedirs(ruta_logs, exist_ok=True)


# 2. COMPROBACIÓN PARA PAUSAR / REANUDAR
if os.path.exists(ruta_checkpoint):
    print(f"🔄 Cargando progreso anterior desde: {ruta_checkpoint}")
    model = keras.models.load_model(ruta_checkpoint)
    epoca_inicial = 5  # Cambia este número según la época donde lo pausaste
else:
    print("🆕 No hay checkpoints previos. Iniciando desde la época 0.")
    epoca_inicial = 0


# =====================================================================
# 3. CONFIGURACIÓN DE CALLBACKS CON SUS RESPECTIVAS RUTAS
# =====================================================================
# Le indicamos al checkpoint dónde guardarse
checkpoint_callback = keras.callbacks.ModelCheckpoint(
    filepath=ruta_checkpoint,
    monitor="val_loss",
    save_best_only=False,
    verbose=1
)

# Le indicamos a TensorBoard dónde guardar los logs
tensorboard_callback = keras.callbacks.TensorBoard(
    log_dir=ruta_logs,
    histogram_freq=1,
    update_freq="epoch"
)


# 4. EJECUTAR ENTRENAMIENTO
batch_size = 128
epochs = 15

history = model.fit(
    x_train,
    y_train,
    batch_size=batch_size,
    epochs=epochs,
    initial_epoch=epoca_inicial,
    validation_split=0.1,
    callbacks=[checkpoint_callback, tensorboard_callback] # Conectados
)

# Commented out IPython magic to ensure Python compatibility.
# 1. Cargar la extensión de TensorBoard en el cuaderno
# %load_ext tensorboard

# 2. Abrir el panel apuntando EXACTAMENTE a la carpeta donde guardaste los logs
# %tensorboard --logdir proyecto_mnist/logs_tensorboard

"""## Evaluate the trained model"""

score = model.evaluate(x_test, y_test, verbose=0)
print("Test loss:", score[0])
print("Test accuracy:", score[1])

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report

# 1. Tu modelo predice las probabilidades para x_test
predicciones_raw = model.predict(x_test)

# Convertimos las predicciones (probabilidades) a números enteros (0 al 9)
y_pred = np.argmax(predicciones_raw, axis=1)

# CONVERSIÓN CRUCIAL: Como usas categorical_crossentropy, pasamos y_test
# de formato One-Hot Vector a números enteros simples.
y_true = np.argmax(y_test, axis=1)

# 2. Calcular la matriz numéricamente
matriz = confusion_matrix(y_true, y_pred)

# 3. Graficar el mapa de calor
plt.figure(figsize=(10, 8))
# Usamos un rango numérico del 0 al 9 para los ejes (asumiendo que es MNIST)
etiquetas_digitos = [str(i) for i in range(matriz.shape[0])]

sns.heatmap(matriz, annot=True, fmt='d', cmap='Blues',
            xticklabels=etiquetas_digitos,
            yticklabels=etiquetas_digitos)

plt.xlabel('Predicciones del Modelo (Predicted)')
plt.ylabel('Valores Reales (True Labels)')
plt.title('Matriz de Confusión - Análisis de Dígitos')
plt.show()

# 4. Imprimir métricas de precisión, recall y F1-score por cada dígito
print("\n--- Reporte de Clasificación Detallado ---")
print(classification_report(y_true, y_pred, target_names=etiquetas_digitos))

"""SAVE_MODEL, SAVE_WEIGTHS"""

# =====================================================================
# 1. GUARDAR AMBAS COSAS MANUALMENTE (Al final del entrenamiento)
# =====================================================================

# Guardar el modelo completo (Arquitectura + Pesos + Configuración)
model.save("modelo_completo_mnist.keras")
print("✅ ¡Modelo completo guardado con éxito en 'modelo_completo_mnist.keras'!")

# Guardar únicamente los pesos (Solo los parámetros numéricos)
model.save_weights("pesos_mnist.weights.h5")
print("✅ ¡Pesos del modelo guardados con éxito en 'pesos_mnist.weights.h5'!")

#!pip install gradio opencv-python

import os
import cv2
import gradio as gr
import numpy as np
import tensorflow as tf
from tensorflow import keras

# =====================================================================
# 1. DEMOSTRACIÓN DE CARGA (Usando tus archivos guardados)
# =====================================================================
# Carga A: Modelo Completo
modelo_completo = keras.models.load_model("modelo_completo_mnist.keras")

# Carga B: Solo Pesos (Reconstruyendo la estructura que definiste antes)
modelo_pesos = keras.Sequential([
    keras.Input(shape=(28, 28, 1)),
    keras.layers.Conv2D(32, kernel_size=(3, 3), activation="relu"),
    keras.layers.MaxPooling2D(pool_size=(2, 2)),
    keras.layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
    keras.layers.MaxPooling2D(pool_size=(2, 2)),
    keras.layers.Flatten(),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(10, activation="softmax"),
])
modelo_pesos.load_weights("pesos_mnist.weights.h5")
print("✅ Archivos cargados correctamente con load_model y load_weights.")

# =====================================================================
# 2. PREPROCESAMIENTO DE TU FOTO EXTERNA
# =====================================================================
def preparar_imagen_externa(ruta_imagen):
    # 1. Leer la foto en escala de grises
    img = cv2.imread(ruta_imagen, cv2.IMREAD_GRAYSCALE)

    # 2. Redimensionar primero a un tamaño mediano para procesar mejor (ej. 100x100)
    img_medium = cv2.resize(img, (100, 100))

    # 3. BINARIZACIÓN OTSU: Separa el texto del fondo de forma inteligente.
    # Convierte el papel en blanco absoluto (255) y la tinta en negro absoluto (0).
    _, img_thresh = cv2.threshold(img_medium, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)

    # 4. DILATACIÓN: Engrosa el trazo simulando un marcador grueso
    kernel = np.ones((3, 3), np.uint8)
    img_thick = cv2.dilate(img_thresh, kernel, iterations=1)

    # 5. Redimensionar finalmente a los 28x28 obligatorios de tu red
    img_resized = cv2.resize(img_thick, (28, 28))

    # 6. Normalizar los píxeles de 0 a 1
    img_normalized = img_resized / 255.0

    # 7. Adaptar la forma para tu modelo de Keras: (1, 28, 28, 1)
    img_final = np.expand_dims(img_normalized, axis=(0, -1))

    return img_final

# =====================================================================
# 3. INTERFAZ WEB INTERACTIVA
# =====================================================================
def predecir_subida(imagen_pil):
    if imagen_pil is None:
        return "Por favor, sube una foto o usa la cámara."

    ruta_temporal = "foto_usuario.png"
    imagen_pil.save(ruta_temporal)

    # Procesar la foto con nuestra función
    tensor_imagen = preparar_imagen_externa(ruta_temporal)

    # Hacer la predicción con el modelo cargado
    prediccion = modelo_completo.predict(tensor_imagen)
    clase = np.argmax(prediccion, axis=1)[0]
    confianza = np.max(prediccion) * 100

    if os.path.exists(ruta_temporal):
        os.remove(ruta_temporal)

    return f"🔢 Dígito Detectado: {clase}\n🎯 Confianza: {confianza:.2f}%"

# Crear el panel de Gradio
demo = gr.Interface(
    fn=predecir_subida,
    inputs=gr.Image(type="pil", label="Sube una foto desde tu PC o usa la cámara de tu cel"),
    outputs=gr.Textbox(label="Resultado de la Red Neuronal"),
    title="Probador MNIST - Carga de Modelos Físicos",
    description="Sube cualquier imagen con un número del 0 al 9 escrito a mano para poner a prueba tu modelo entrenado."
)

# Lanzar la app con link compartido para abrir en el celular
demo.launch(share=True)

"""## Relevant Chapters from Deep Learning with Python
- [Chapter 8: Image classification](https://deeplearningwithpython.io/chapters/chapter08_image-classification)

"""
